/***************************************************************************
 *
 *   RunUO                   : May 1, 2002
 *   portions copyright      : (C) The RunUO Software Team
 *   email                   : info@runuo.com
 *   
 *   Angel Island UO Shard   : March 25, 2004
 *   portions copyright      : (C) 2004-2024 Tomasello Software LLC.
 *   email                   : luke@tomasello.com
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

/*   changelog.
 *   9/16/04,Lego
 *           Changed Display Name of deed 
 *
 *
 *
 */
/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////

namespace Server.Items
{
    public class TrinsicLargeAddon : BaseAddon
    {
        public override BaseAddonDeed Deed
        {
            get
            {
                return new TrinsicLargeAddonDeed();
            }
        }

        public override bool BlocksDoors { get { return false; } }
        public override bool Redeedable { get { return true; } }

        [Constructable]
        public TrinsicLargeAddon()
        {
            AddonComponent ac = null;
            ac = new AddonComponent(2778);
            AddComponent(ac, -2, -2, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, -2, -1, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, -2, 0, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, -2, 1, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, -2, 2, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, -1, -2, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, -1, -1, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, -1, 0, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, -1, 1, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, -1, 2, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 0, -2, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 0, -1, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 0, 0, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 0, 1, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 0, 2, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 1, -2, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 1, -1, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 1, 0, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 1, 1, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 1, 2, 0);
            ac = new AddonComponent(2780);
            AddComponent(ac, -3, -3, 0);
            ac = new AddonComponent(2781);
            AddComponent(ac, -3, 3, 0);
            ac = new AddonComponent(2783);
            AddComponent(ac, -3, -2, 0);
            ac = new AddonComponent(2783);
            AddComponent(ac, -3, -1, 0);
            ac = new AddonComponent(2783);
            AddComponent(ac, -3, 0, 0);
            ac = new AddonComponent(2783);
            AddComponent(ac, -3, 1, 0);
            ac = new AddonComponent(2783);
            AddComponent(ac, -3, 2, 0);
            ac = new AddonComponent(2784);
            AddComponent(ac, -2, -3, 0);
            ac = new AddonComponent(2784);
            AddComponent(ac, -1, -3, 0);
            ac = new AddonComponent(2784);
            AddComponent(ac, 0, -3, 0);
            ac = new AddonComponent(2784);
            AddComponent(ac, 1, -3, 0);
            ac = new AddonComponent(2786);
            AddComponent(ac, -2, 3, 0);
            ac = new AddonComponent(2786);
            AddComponent(ac, -1, 3, 0);
            ac = new AddonComponent(2786);
            AddComponent(ac, 0, 3, 0);
            ac = new AddonComponent(2786);
            AddComponent(ac, 1, 3, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 2, -2, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 2, -1, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 2, 0, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 2, 1, 0);
            ac = new AddonComponent(2778);
            AddComponent(ac, 2, 2, 0);
            ac = new AddonComponent(2779);
            AddComponent(ac, 3, 3, 0);
            ac = new AddonComponent(2782);
            AddComponent(ac, 3, -3, 0);
            ac = new AddonComponent(2784);
            AddComponent(ac, 2, -3, 0);
            ac = new AddonComponent(2785);
            AddComponent(ac, 3, -2, 0);
            ac = new AddonComponent(2785);
            AddComponent(ac, 3, -1, 0);
            ac = new AddonComponent(2785);
            AddComponent(ac, 3, 0, 0);
            ac = new AddonComponent(2785);
            AddComponent(ac, 3, 1, 0);
            ac = new AddonComponent(2785);
            AddComponent(ac, 3, 2, 0);
            ac = new AddonComponent(2786);
            AddComponent(ac, 2, 3, 0);

        }

        public TrinsicLargeAddon(Serial serial)
            : base(serial)
        {
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write(0); // Version
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    public class TrinsicLargeAddonDeed : BaseAddonDeed
    {
        public override BaseAddon Addon
        {
            get
            {
                return new TrinsicLargeAddon();
            }
        }

        [Constructable]
        public TrinsicLargeAddonDeed()
        {
            Name = "Trinsic Large Carpet";
        }

        public TrinsicLargeAddonDeed(Serial serial)
            : base(serial)
        {
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write(0); // Version
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }
}