/***************************************************************************
 *
 *   RunUO                   : May 1, 2002
 *   portions copyright      : (C) The RunUO Software Team
 *   email                   : info@runuo.com
 *   
 *   Angel Island UO Shard   : March 25, 2004
 *   portions copyright      : (C) 2004-2024 Tomasello Software LLC.
 *   email                   : luke@tomasello.com
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////

namespace Server.Items
{
    public class TeleporterBoatWestAddon : BaseAddon
    {
        public override BaseAddonDeed Deed
        {
            get
            {
                return new TeleporterBoatWestAddonDeed();
            }
        }

        [Constructable]
        public TeleporterBoatWestAddon()
        {
            AddonComponent ac = null;
            ac = new AddonComponent(16060);
            AddComponent(ac, 1, -4, 0);
            ac = new AddonComponent(16046);
            AddComponent(ac, 1, -2, 0);
            ac = new AddonComponent(16028);
            AddComponent(ac, 2, -2, 0);
            ac = new AddonComponent(16027);
            AddComponent(ac, 0, -2, 0);
            ac = new AddonComponent(16026);
            AddComponent(ac, 1, -3, 0);
            ac = new AddonComponent(16085);
            AddComponent(ac, -1, 1, 0);
            ac = new AddonComponent(16064);
            AddComponent(ac, 1, 3, 0);
            ac = new AddonComponent(16054);
            AddComponent(ac, 0, 3, 0);
            ac = new AddonComponent(16044);
            AddComponent(ac, 1, 1, 0);
            ac = new AddonComponent(16060);
            AddComponent(ac, 1, 4, 0);
            ac = new AddonComponent(16048);
            AddComponent(ac, 1, 0, 0);
            ac = new AddonComponent(16045);
            AddComponent(ac, 1, -1, 0);
            ac = new AddonComponent(16044);
            AddComponent(ac, 1, 2, 0);
            ac = new AddonComponent(16043);
            AddComponent(ac, 2, 3, 0);
            ac = new AddonComponent(16040);
            AddComponent(ac, 2, 2, 0);
            ac = new AddonComponent(16039);
            AddComponent(ac, 0, 2, 0);
            ac = new AddonComponent(16038);
            AddComponent(ac, 2, 1, 0);
            ac = new AddonComponent(16033);
            AddComponent(ac, 0, 1, 0);
            ac = new AddonComponent(16032);
            AddComponent(ac, 2, 0, 0);
            ac = new AddonComponent(16031);
            AddComponent(ac, 0, 0, 0);
            ac = new AddonComponent(16030);
            AddComponent(ac, 2, -1, 0);
            ac = new AddonComponent(16029);
            AddComponent(ac, 0, -1, 0);

        }

        public TeleporterBoatWestAddon(Serial serial)
            : base(serial)
        {
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write(0); // Version
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    public class TeleporterBoatWestAddonDeed : BaseAddonDeed
    {
        public override BaseAddon Addon
        {
            get
            {
                return new TeleporterBoatWestAddon();
            }
        }

        [Constructable]
        public TeleporterBoatWestAddonDeed()
        {
            Name = "TeleporterBoatWest";
        }

        public TeleporterBoatWestAddonDeed(Serial serial)
            : base(serial)
        {
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write(0); // Version
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }
}